### ISSUE TITLE
Missing resource group for subnet

### ISSUE THREAD

**Issue by l2fprod** [lionelmace/mytodo#8]
Right now, the subnets are created in the default resource group... they should be created under the same resource group as the VPC

https://github.com/lionelmace/mytodo/blob/1a2dd0acec60bd0b8c52b39674992367bb407d6b/cloud/terraform/networking-vpc.tf#L139

**Comment by lionelmace** [comment]
Fixed in commit b6f01d2254732bd8c2e5ac84a739572a2f72dccd
